- hosts: localhost
  tasks:
    - parcels:
        cm_host: localhost
        cm_username: admin
        cm_password: admin
        parcel_version: 5.8.4-1.cdh5.8.4.p0.5
        action: distribute
      register: cm

    - debug: var=cm
