---
- name: Install extra yum repository
  copy: >
    src=cloudera-cdh5.repo
    dest=/etc/yum.repos.d
    mode=0664
    backup=yes
  tags:
   - yum

- name: Add a Cloudera Repository Key.
  shell: >
    rpm --import https://archive.cloudera.com/redhat/cdh/RPM-GPG-KEY-cloudera
  tags:
   - yum

- name: Install Cloudera Server and httpd rpm packages
  yum: >
    name={{item}}
    state=latest
  with_items:
  - cloudera-manager-server
  - cloudera-manager-daemons
  tags: 
   - yum

- name: Chmod Cloudera Manager Server configuration folder
  file: >
    path=/etc/cloudera-scm-server
    state=directory
    mode=0664
    group=cloudera-scm
    recurse=true
  tags:
   - cm

- name: Chmod Cloudera Manager Server configuration file
  file: >
    path=/etc/default/cloudera-scm-server
    state=file
    mode=0664
    group=cloudera-scm
  tags:
   - cm

- name: Disable SELinux
  selinux: >
    state=disabled
  tags:
   - cm

- name: Enable Cloudera Manager Server services autostart
  service: >
    name={{item}}
    enabled=yes
  with_items:
    - cloudera-scm-server
  tags:
   - cm

- name: Ensure Cloudera Manager Server services are started
  service: >
    name={{item}}
    state=started
  with_items:
    - cloudera-scm-server-db
    - cloudera-scm-server
  tags:
   - cm
