- name: "Wait for host to contact cloudera manager server"
  pause:
    seconds: 30
- name: "Add Node to cluster"
  hosts:
    cm_host: "{{cm_host}}"
    cm_username: "{{cm_username}}"
    cm_password: "{{cm_password}}"
    hostname: "{{ item.private_dns_name }}"
    action: add
  register: cm
  with_items: "{{ ec2.instances }}"
- debug: msg="{{cm}}"
- name: "Distribute Parcels"
  parcels:
    cm_host: "{{cm_host}}"
    cm_username: "{{cm_username}}"
    cm_password: "{{cm_password}}"
    parcel_version: "{{parcel_version}}"
    action: distribute
  register: parcel
- debug: msg="{{parcel}}"
- name: "Assign host template"
  template:
    cm_host: "{{cm_host}}"
    cm_username: "{{cm_username}}"
    cm_password: "{{cm_password}}"
    hostname: "{{ item.private_dns_name }}"
    template_name: "m3-medium-worker"
  register: template
- debug: msg="{{template}}"
